spring:
  profiles:
<<<<<<< HEAD
    active: localdb
server:
  port: 8082
=======
    active: local
>>>>>>> 730682769406a2a2f368ba880e55b37e4d97bf76

---

spring:
  profiles:
    group:
      "local": "localdb,common"
      "dev": "devdb,common"

---

spring:
  config:
    activate:
      on-profile: "devdb"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://petcomes.cnccg3mescgh.ap-northeast-2.rds.amazonaws.com:3306/petcomes?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: petcomes
    password: petcomes

---

spring:
  config:
    activate:
      on-profile: "localdb"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
<<<<<<< HEAD
    url: jdbc:mysql://127.0.0.1:3306/petcomes?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: gm040404@
=======
    url: jdbc:mysql://127.0.0.1:3306/petComes?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: Heather
    password: HeatherMySQL
>>>>>>> 730682769406a2a2f368ba880e55b37e4d97bf76

---

spring:
  config:
    activate:
      on-profile: "common"
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect



